# Define ARG variables for the build
ARG CLICKHOUSE_SERVER_VERSION="25-debian-dev"

# Use production ready docker hardened images - https://hub.docker.com/hardened-images/catalog/dhi/prometheus
FROM dhi.io/clickhouse-server:${CLICKHOUSE_SERVER_VERSION}
