# Define ARG variables for the build
ARG GRAFANA_VERSION="13-debian-dev"

# Use production ready docker hardened images - https://hub.docker.com/hardened-images/catalog/dhi/grafana
FROM dhi.io/grafana:${GRAFANA_VERSION}