# Define ARG variables for the build
ARG MONGODB_VERSION="8-debian-dev"

# Use production ready docker hardened images - https://hub.docker.com/hardened-images/catalog/dhi/trino
FROM dhi.io/mongodb:${MONGODB_VERSION}

